<?php

return [
    'role' => [
        'browse_role',
        'view_role',
        'create_role',
        'update_role',
        'delete_role',
        'assign_role',
    ],
    'permission' => [
        'browse_permission',
        'grant_permission',
        'revoke_permission',
    ],
    'user' => [
        'browse_user',
        'view_user',
        'create_user',
        'update_user',
        'update_user_permissions',
        'delete_user',
    ],
    'customer' => [
        'browse_customer',
        'view_customer',
        'create_customer',
        'update_customer',
        'delete_customer',
        'browse_customer_comment',
        'create_customer_comment',
    ],
    'package' => [
        'browse_package',
        'view_package',
        'create_package',
        'update_package',
        'delete_package',
    ],
    'comment' => [
        'update_comment',
        'delete_comment',
    ],
    'order' => [
        'browse_order',
        'view_order',
        'create_order',
        'update_order',
        'delete_order',
        'browse_order_comment',
        'create_order_comment',
    ],
    'event' => [
        'browse_event',
        'view_event',
        'create_event',
        'update_event',
        'delete_event',
    ],
    'visit' => [
        'browse_visit',
        'view_visit',
        'create_visit',
        'update_visit',
        'delete_visit',
    ],
    'report' => [
        'browse_report',
        'view_report',
        'create_report',
        'update_report',
        'delete_report',
    ],
    'accounting' => [
        'browse_accounting',
        'view_accounting',
        'create_accounting',
        'update_accounting',
        'delete_accounting',
    ],
    'stock' => [
        'browse_stock',
        'view_stock',
        'create_stock',
        'update_stock',
        'delete_stock',
    ],
    'buffet_order' => [
        'browse_buffet_order',
        'view_buffet_order',
        'create_buffet_order',
        'update_buffet_order',
        'delete_buffet_order',
    ],
    'statistics' => [
        'browse_statistics',
    ],
    'home' => [
        'browse_home',
    ],
    'suppliers' => [
        'browse_supplier',
        'view_supplier',
        'create_supplier',
        'update_supplier',
        'delete_supplier',
    ],
    'employers' => [
        'browse_employer',
        'view_employer',
        'create_employer',
        'update_employer',
        'delete_employer',
    ],
    'operations' => [
        'browse_operation',
        'view_employer',
        'create_employer',
        'update_employer',
        'delete_employer',
    ],
];
